LetsHack.c
This is my first C program upload in any repo in GITHUB
:D
=> Added a c program

s.c
=> C program for finding out the Area of rectangle

Avg_array..c
It will add the elements of the array and find the average of the elements of the Array.
=> It will take element from the user and find the average of the elements

Bubble-sort
=> Created bubble sort

#include stdio.h/Name - Neeraj Singh/reg No - 12012889/Vowelchecker.c, Power_of_N.c
Hii, If you like my contribution so please accept it and merge in main branch.
=> Calculate power of a number

ArmstrongNumber.c
This program will take number as input and check if it is Armstrong number or not.
=> Added C program to check if entered number is Armstrong Number or Not.

array sum
=> Create array sum

Array Duplicacy
Removing Duplicate Elements in Array
=> Create Array Duplicacy

No of Duplicate Elements
Count the Number of Duplicate elements
=> Create No of Duplicate Elements

bubblesort
This is bubble sort implementation in C.
=> bubblesort

Start_Patterns.c
Start Pattern C Program Added, This C Program Help Other C Developers (Beginners) To Learn Basic Loops And Enhanced Their Nested Loop Structure Knowledge.
=> Start Pattern C Program Added

Armstrong_no.c
hope you find it better and straight.
=> Just modified a bit

palindrome_pyramid_pattern.c
Displaying palindrome pyramid pattern
=> palindrome_pyramid_pattern.c

number_triangle.c
=> number_triangle.c

Pascal_Triangle.c
=> Added the famous Pascal's Triangle

Kosaruju.cpp, kruskals.cpp, prims.cpp
Added code for Kruskals, prims, and Kosaraju algorithms where Kruskals and prims are algorithms to find the Minimum spanning tree and Kosaraju to determine the single connected components in the graph.
=> Prims, Kruskal and Kosaraju algorithms

No of Duplicate Elements
I have Changed the name of the limit of an array and I had also printed the duplicate element and the count of duplicate elements...
=> Update No of Duplicate Elements

break.c
I have written a program on break.c
=>  break in C

stack_infix_prefix.c, stack_postfix_infix.c, stack_postfix_val.c
1.infix to prefix
eg. input: a*b+(c-d/e)+f/(g+h)
output: ++*ab-c/de/f+gh
2.postfix to infix
eg: input: ab+cde/+g*-h+
output: (((a+b)-((c+(d/e))*g))+h)
3.postfix evaluation
eg: input: 34+
output: 7
(only for single digit operands)
=> added stack programs in c

QueueUsingArray.c
Implementation of queue using array
Language: C
please add this under hacktoberfest 2021
=> Created QueueUsingArray.c

crediti.c
=> Added c program to check if credit card if vaild
